package: v20240514
generate:
  client: true
  models: true
output-options:
  skip-prune: true
import-mapping:
  ./common/common.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/common
  ./links/links.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/links
  ./workspaces/workspaces.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/workspaces
  ./parameters/orgs.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/parameters
  ./parameters/request-id.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/parameters
  ./parameters/user-agent.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/parameters
  ./parameters/content-type.yaml: github.com/snyk/code-client-go/internal/workspace/2024-05-14/parameters
output: client.go